name: mlp2
shuffle: true
drop_last: false
max_epoch: 20
patience: 10
use_best_param: true
compare:
  optimizer:
    - name: MomentumSGD
      params:
        beta: 0.9
  scheduler:
    - name: ExpDecayLR
      params:
        init: 1
        alpha: 0.96
  batch_size:
    - 256
grid_search:
  learning_rate:
    - 0.0001
  l2_lambda:
    - 0.00001
  hidden_size:
    - 512
